apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        io.kompose.service: nginx-proxy-claim1
    name: nginx-proxy-claim1
spec:
    accessModes:
        - ReadOnlyMany
    resources:
        requests:
            storage: 100Mi
